version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "terridb"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    allow:
      - dependency-type: "all"
    ignore:
    # Add any packages to ignore
    # - dependency-name: "lodash"

  # Enable version updates for Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:30"
    reviewers:
      - "terridb"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "terridb"