# Build
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
#RUN npm run build

# Production
FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app .
RUN npm prune --omit=dev
USER node
CMD ["node", "src/index.js"]