# name: Security Scan

# on:
#   schedule:
#     - cron: '0 2 * * *' # Runs daily at 2:00 AM

# jobs:
#   scan:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v6
#       - uses: actions/setup-node@v6
#         with:
#           node-version: 'lts/*'
#       - run: npm audit --audit-level=moderate
